fix copilot skill sample failing on arg mismatch - update semantic-kernel version to 1.28.1 - update `agent.get_response` usage to new contract - use openai API key parameter Steps to reproduce: see [README](https://github.com/microsoft/semantic-kernel/tree/main/python/samples/demos/copilot_studio_skill)
The error is caused by arg mismatch between `get_response()` and `ChatCompletionAgent._inner_invoke()`:
```
  File "/usr/local/lib/python3.12/site-packages/teams/app.py", line 884, in _on_activity
    if not await route.handler(context, state):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bot.py", line 62, in on_message
    sk_response = await agent.get_response(history=chat_history, user_input=user_message)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/semantic_kernel/utils/telemetry/agent_diagnostics/decorators.py", line 69, in wrapper_decorator
    return await get_response_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/semantic_kernel/agents/chat_completion/chat_completion_agent.py", line 275, in get_response
    async for response in self._inner_invoke(
                          ^^^^^^^^^^^^^^^^^^^
TypeError: ChatCompletionAgent._inner_invoke() got multiple values for argument 'history'
INFO:aiohttp.access:100.100.0.93 [28/Apr/2025:07:25:07 +0000] "POST /api/messages HTTP/1.1" 200 3597 "-" "Microsoft-BotFramework/3.1 BotBuilder/4.23.0.0 .NETCoreAppVersion/v8.0"
```